---
- name: install,uninstall and update s/w package
  hosts: all
  vars:
    - a: tomcat8
    - b: present
    - c: no
  tasks:
    - name: install s/w
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...
#the above playbook works like a template whose default behavior is to bypass that behavior and make it work on some other data by passing it as a global veriable using --extra-vars option
#command---- ansible-playbook playbook(playscop).yml --extra-vars "a=tree" -b



